#before_script:
#  - yum install -y gsl-devel boost-devel

build:
  tags:
    - cvmfs
  script:
    - export USER=TestUser
    - source /cvmfs/lhcb.cern.ch/group_login.sh --no-userarea
    - source setup.sh
